from tkinter import *

root=Tk()
root.geometry("1280x700")
root.title("Bus Ticketing System")
root.configure(background="black")

left=Frame(root, width=777, height=650,bd=5,relief="raise")
left.pack(side=LEFT, fill=Y)
right=Frame(root, width=500, height=650,bd=5,relief="raise")
right.pack(side=RIGHT, fill=Y)

top=Frame(left, width=600, height=200)
top.pack(side=TOP, fill=Y)
toplabel=Label(top,text="Passenger Information",font=("times",32,"bold"),height=2)
toplabel.pack()

f1=Frame(left, width=600, height=500,bd=4)
f1.pack(side=TOP, fill=Y)
label1=Label(f1,text="Name ",font=("times",32,"bold"),height=2)
label1.grid(row=1,column=1,sticky=W)
label1=Label(f1,text="Email ",font=("times",32,"bold"),height=2)
label1.grid(row=2,column=1,sticky=W)
label1=Label(f1,text="Mobile No. ",font=("times",32,"bold"),height=2)
label1.grid(row=3,column=1,sticky=W)

entry1=Entry(f1,font=("times",30,"bold"),bd=4)
entry1.grid(row=1,column=2,sticky=W)
entry2=Entry(f1,font=("times",30,"bold"),bd=4)
entry2.grid(row=2,column=2,sticky=W)
entry3=Entry(f1,font=("times",30,"bold"),bd=4)
entry3.grid(row=3,column=2,sticky=W)

bb=Button(f1,text="Done ",font=("times",30,"bold"),bd=4)
bb.grid(row=4,column=3,sticky=E)

topright=Frame(right, width=500, height=345,bd=5,relief="raise")
topright.pack(side=TOP, fill=Y)
bottomright=Frame(right, width=500, height=340,bd=5,relief="raise")
bottomright.pack(side=BOTTOM, fill=Y)

topright1=Frame(topright, width=500, height=50)
topright1.pack(side=TOP, fill=Y)
labelr1=Label(topright1,text="Journey Details ",font=("times",30,"bold"))
labelr1.pack(fill=X)

topright2=Frame(topright, width=500, height=290)
topright2.pack(side=TOP, fill=Y)
labelr1=Label(topright2,text="Journey: ",font=("times",20,"bold"),height=2)
labelr1.grid(row=1,column=1,sticky=W)
labelr2=Label(topright2,text="Depart Time: ",font=("times",20,"bold"),height=2)
labelr2.grid(row=2,column=1,sticky=W)
labelr3=Label(topright2,text="Depart Date: ",font=("times",20,"bold"),height=2)
labelr3.grid(row=3,column=1,sticky=W)

labelr4=Label(topright2,width=18,height=2,relief='sunken',bd=4)
labelr4.grid(row=1,column=2,sticky=W,columnspan=2)
labelr8=Label(topright2,text=" to ",font=("times",20,"bold"))
labelr8.grid(row=1,column=3,sticky=W)
labelr5=Label(topright2,width=18,height=2,relief='sunken',bd=4)
labelr5.grid(row=1,column=4,sticky=W,columnspan=2)
labelr6=Label(topright2,width=18,height=2,relief='sunken',bd=4)
labelr6.grid(row=2,column=2,sticky=W)
labelr7=Label(topright2,width=18,height=2,relief='sunken',bd=4)
labelr7.grid(row=3,column=2,sticky=W)
labelrs=Label(topright2,text="Seats: ",font=("times",20,"bold"),height=2)
labelrs.grid(row=4,column=1,sticky=W)
labelrss=Label(topright2,width=18,height=2,relief='sunken',bd=4)
labelrss.grid(row=4,column=2,sticky=W)
labelrp=Label(topright2,text="Pick up: ",font=("times",20,"bold"),height=1)
labelrp.grid(row=5,column=1,sticky=W)
labelrpp=Label(topright2,width=18,height=2,relief='sunken',bd=4)
labelrpp.grid(row=5,column=2,sticky=W)

bottomright1=Frame(bottomright, width=500, height=50)
bottomright1.pack(side=TOP, fill=Y)
labelb1=Label(bottomright1,text="Price Details ",font=("times",30,"bold"),height=2)
labelb1.pack(fill=Y)

bottomright3=Frame(bottomright, width=500, height=250)
bottomright3.pack(side=TOP, fill=Y)
labelb1=Label(bottomright3,text="Journey Fare:- ",font=("times",28,"bold"),width=12,height=1)
labelb1.grid(row=1,column=1,sticky=W)
labelb2=Label(bottomright3,text="Base Fare: ",font=("times",24,"bold"),height=2)
labelb2.grid(row=2,column=1,sticky=W)
labelb3=Label(bottomright3,text="Total Base Fare: ",font=("times",24,"bold"),height=2)
labelb3.grid(row=3,column=1,sticky=W)
labelb4=Label(bottomright3,width=25,relief='sunken',bd=4,font=("times",18))
labelb4.grid(row=2,column=2,sticky=W)
labelb5=Label(bottomright3,width=25,relief='sunken',bd=4,font=("times",18))
labelb5.grid(row=3,column=2,sticky=W)


root.mainloop()